### PR TITLE
Enable the ability to specify a ini file

### PR DESCRIPTION
**Pull request by Borillion**
Allow for the ability to specify what ini file to use with a test.

ie. $ ./fdb_bench /.../some_folder/sample.ini

### CODE REVIEW

**Comment by greensky00** [comment]
Hi Borillion,

Thanks for your contributions. I agree that the INI file name has to be configurable by users. 

However, your commit needs to be changed a little bit since the current benchmark program already uses argv[...] parameters to identify "--e" or "-e" flag (it is used to skip initialization phase). Hence, instead of using argv[1], I think the desirable behavior would be as follows:

1) If argv[n] == "--c" or "-c", then
2) Set the INI file name to argv[n+1].
3) Otherwise (there is no "--c" flag), use the default INI file name (i.e., bench_config.ini).

If you would like me to make those additional changes, please feel free to let me know. Then I will merge your commit first, and upload a separate commit.

Thanks.

**Comment by Borillion** [comment]
Thanks, I will make the changes and make a second commit soon.

**Comment by Borillion** [comment]
greensky00 can you please take a look at https://github.com/Borillion/ForestDB-Benchmark/tree/Borillion-patch-1-1 , I believe this meets all the requirements and preserves the --e/-e option.

Thanks

**Comment by greensky00** [comment]
Verified and merged. Thanks for your contributions!

**Pull request merged**
